name: CICD for Serverless Application-title of action
run-name: ${{github.actor}} is doing CICD for serverless application

on: 
  push:
    branches: [ main, "*"]

jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job is automatically triggered by a ${{ github.event.name }} event."

  install-dependencies:
    runs-on: ubuntu-latest
    needs: pre-deploy
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run installation of dependencies commands
        run: npm install

  unit-testing:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run installation of dependencies commands
        run: npm install
      - name: Run unit testing command
        run: npm test


  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: unit-testing
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy
        env:
           - name: Get secrets by name and by ARN
             uses: aws-actions/aws-secretsmanager-get-secrets@v1
             with:
               secret-ids: |
                yuyuan-secret
                arn:aws:secretsmanager:ap-southeast-1:255945442255:secret:yuyuan-secret-72ZuiP
                0/test/secret
                /prod/example/secret
                SECRET_ALIAS_1,test/secret
                SECRET_ALIAS_2,arn:aws:secretsmanager:ap-southeast-1:255945442255:secret:yuyuan-secret-72ZuiP